version: '3'

services:
  nats-server:
    image: nats:latest
  
  client-gateway:
    build: 
      context:  ./client-gateway
      dockerfile: dockerfile.prod
    image:  client-gateway-prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=3000
      - NATS_SERVERS=${NATS_SERVERS}

  auth-ms:
    build: 
      context:  ./auth-ms
      dockerfile: dockerfile.prod
    image:  auth-ms-prod
    environment:
      - PORT=3004
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${AUTH_DB_URL}
      - JWT_SECRET=${JWT_SECRET}

  payments-ms:
    container_name: payments-ms
    build: 
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: payments-ms-prod
    environment:
      - PORT=3003
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}

  products-ms:
    build: 
      context:  ./products-ms
      dockerfile: dockerfile.prod
    image: products-ms-prod
    environment:
      - PORT=3001
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=file:./dev.db

  orders-ms:
    build: 
      context:  ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DB_URL=${ORDERS_DB_URL}
    image:  orders-ms-prod
    environment:
      - PORT=3002
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${ORDERS_DB_URL}
